### ISSUE TITLE
timeCounter test doesn't seem to be testing the correct thing

### ISSUE THREAD

**Issue by joeylouise** [FAC10/week2-LZ#35]
I think that this test isn't running what you want it to - it says it's testing that `timeCounter` increases by 1 each time the function is run, but `timeCounter` doesn't increase at all (it's always 1). Should it test that `time` increases by 1 each time?

https://github.com/FAC10/week2-LZ/blob/master/tests/tests.js#L16

**Comment by ZooeyMiller** [comment]
That is totally fair! This was when we were trying to just write tests for anything we could, and you're right, all this tests is that we have defined the `time counter` as what we say we have.

Going to remove the test since it's a bit pointless.

**Comment by joeylouise** [comment]
@ZooeyMiller 👍 😄
